### ISSUE TITLE
데이터셋 찾기

### ISSUE THREAD

**Issue by Haeinnnn** [Haeinnnn/geonganghaeGYM#1]
찾은 데이터셋의 링크를 올려주세요

**Comment by Haeinnnn** [comment]
https://www.kaggle.com/datasets/sahasradityathyadi/posture-recognition

**Comment by gaeun0506** [comment]
척추측만증 데이터 (YES)
https://www.kaggle.com/datasets/akbotayelemessova/scoliosis-back-images-yes?select=22+%282%29.jpg

척추측만증 데이터 (NO)
https://www.kaggle.com/datasets/akbotayelemessova/scoliosis-screening-no?select=20+%2814%29.jpg

**Comment by Hwang-sg** [comment]
https://www.itm-conferences.org/articles/itmconf/pdf/2021/05/itmconf_icacc2021_03031.pdf
(Pose estimation and Correcting Exercise posture)논문 참고용

**Comment by thewLHE** [comment]
1.데이터
http://human-pose.mpi-inf.mpg.de/#dataset
2.모델
https://paperswithcode.com/task/pose-estimation
3.일어선 자세 / 앉은 자세 부 참고 링크
1)일어선자세
https://hani75.co.kr/572
2)앉은 자세
https://m.health.chosun.com/svc/news_view.html?contid=2007090401060

**Comment by Haeinnnn** [comment]
직접 찍은 데이터로 구글 공유 드라이브에 정리하여 업로드
데이터 셋이 모자랄 수 있으니 모델 완성까지 close 하지 않음

**Comment by Haeinnnn** [comment]
고생하셨습니다!
