### ISSUE TITLE
사진　리사이즈　후　크롭하기

### ISSUE THREAD

**Issue by Hwang-sg** [Haeinnnn/geonganghaeGYM#11]

**Comment by Hwang-sg** [comment]
세로기준 1500픽셀로 고정하여 전체 리사이즈했습니다.

**Comment by Haeinnnn** [comment]
stand train bad 1,2,3,4 사진들을 300x1000 (평균)으로 크롭 완료했습니다!

**Comment by thewLHE** [comment]
stand train good / sit test 사진들 크롭 완료 하였습니다

**Comment by gaeun0506** [comment]
sit train good / stand test 사진들 크롭 완료했습니다.
