### ISSUE TITLE
openpose를 사용해서 각도 구하기

### ISSUE THREAD

**Issue by gaeun0506** [Haeinnnn/geonganghaeGYM#12]
관련 자료를 찾아 링크를 코멘트란에 올려주세요

**Comment by gaeun0506** [comment]
https://www.wenyanet.com/opensource/ko/6114cce81e7105731a0897a4.html

**Comment by Hwang-sg** [comment]
https://www.youtube.com/watch?v=OoNDu9B3CjQ&list=LLMpM7jwStPsrF7s7LeSuxhA&index=1

https://github.com/lxaw/PoseAngleEstimation

**Comment by Haeinnnn** [comment]
https://blog.naver.com/PostView.naver?blogId=rheesungjun&logNo=222366320312

파이썬으로 x, y축의 좌표의 각도를 구하는걸로 찾아봤어요

**Comment by Hwang-sg** [comment]
https://www.youtube.com/watch?v=NmRt9kdUefk&ab_channel=Murtaza%27sWorkshop-RoboticsandAI (opencv angle detection)

**Comment by Hwang-sg** [comment]
https://jesk.or.kr/archive/detail/247?is_paper=y

**Comment by Haeinnnn** [comment]
https://www.kosha.or.kr/kosha/business/ergonomics_e_j.do

**Comment by Haeinnnn** [comment]
고생하셨습니다
