### ISSUE TITLE
사진 라벨링 후 드라이브에 올리기 

### ISSUE THREAD

**Issue by Hwang-sg** [Haeinnnn/geonganghaeGYM#4]
이름 겹치면 오류 날 수 있으니 본인이름(영어약자)으로 라벨링 후 올려서 데이터 이름 안 겹치게 드라이브에 올려주세요!

**Comment by Hwang-sg** [comment]
예시 hsg-good-0818-1 2 3 4 이렇게 해주면 될거같아요

**Comment by Haeinnnn** [comment]
사진 분류 작업은 서경님이 해주셨습니다 감사합니다~!
