### ISSUE TITLE
Callback에 모델체크포인트를 섞어서 저장하는 모델 만들어보기

### ISSUE THREAD

**Issue by Haeinnnn** [Haeinnnn/geonganghaeGYM#6]
참고자료: 라쿤모델, Callback 모델체크포인트 템플릿을 활용
각자 코드부분에 업로드

**Comment by Haeinnnn** [comment]
https://github.com/Haeinnnn/geonganghaeGYM/blob/main/%EC%BD%94%EB%93%9C/0818_open_pose_using_template_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb

**Comment by Hwang-sg** [comment]
https://github.com/Haeinnnn/geonganghaeGYM/blob/main/%EC%BD%94%EB%93%9C/STAND_0823.ipynb

**Comment by gaeun0506** [comment]
https://github.com/Haeinnnn/geonganghaeGYM/blob/main/%EC%BD%94%EB%93%9C/open_pose_%EC%B2%B4%ED%81%AC_%ED%8F%AC%EC%9D%B8%ED%8A%B8%EC%9A%A9_%EC%82%AC%EB%B3%B8%5B%EC%98%A4%EB%A5%98%EB%B0%9C%EC%83%9D%5D.ipynb

**Comment by thewLHE** [comment]
https://github.com/Haeinnnn/geonganghaeGYM/blob/main/%EC%BD%94%EB%93%9C/GYM_v2_4.ipynb

**Comment by Haeinnnn** [comment]
코드선정은

https://github.com/Haeinnnn/geonganghaeGYM/blob/main/%EC%BD%94%EB%93%9C/STAND_0823.ipynb
https://github.com/Haeinnnn/geonganghaeGYM/blob/main/%EC%BD%94%EB%93%9C/GYM_v2_4.ipynb

로 했습니다 감사합니다!
