### ISSUE TITLE
이미지 전부(폴더)를 알아서 자른 후 저장할 수 있는 함수 만들기

### ISSUE THREAD

**Issue by Haeinnnn** [Haeinnnn/geonganghaeGYM#9]
사람을 인식하여 자르는 코드는 현재 한장씩 잘라 저장시키는 방법이기 때문에
폴더에 있는 이미지들을 한번 실행으로 잘라서 저장시킬 수 있는 for문을 짠 뒤 업로드해주세요

**Comment by gaeun0506** [comment]
[해결 코드]
https://github.com/Haeinnnn/geonganghaeGYM/blob/main/%EC%BD%94%EB%93%9C/0826_GYM_v2_5%5Bexcept_open_pose%5D.ipynb
